datadir : '/root/ethereum/eth1/data/'
port : "30303"
chain : "mainnet"
identity : "RPC ethereum mainnet"
db.size.limit : "4TB"
nat : "extip:Your Public IP"
http : "true"
http.addr : "0.0.0.0"
http.port : "8545"
http.vhosts : "*"
http.api : ["eth","engine","debug","net","trace","web3","erigon","txpool","admin","ots"]
ws : "true"
ws.port : "8546"
torrent.port : "42069"
torrent.download.rate : "900mb"
metrics : "true"
metrics.addr : "127.0.0.1"
metrics.port : "6060"
diagnostics.endpoint.addr : "127.0.0.1"
diagnostics.endpoint.port : "6060"
beacon.api.addr : "0.0.0.0"
beacon.api.port : "5555"
beacon.api.cors.allow-methods : ["GET","POST","PUT","OPTIONS"]
beacon.api.cors.allow-origins : "*"
beacon.api : ["beacon","builder","config","debug","node","lighthouse"]
private.api.addr : "localhost:9090"
internalcl : "true"
#txpool.globalbasefeeslots : "100000"
#txpool.globalqueue : "100000"
#txpool.globalslots : "30000"
